e404:
  path:
  controller: ThinApp\Controller\NotFound404Controller

root:
  path: /
  controller: ThinApp\Controller\HomeController

home:
  path: /home
  controller: ThinApp\Controller\HomeController

actionTest:
  path: /action-test
  controller: ThinApp\Controller\ActionTestController
  action: testMethod

student:
  path: /students/{student_id}
  controller: ThinApp\Controller\StudentController

studentScore:
  path: /students/{student_id}/scores/{score_id}
  controller: ThinApp\Controller\StudentController
  action: scoreAction
